### ISSUE TITLE
所以只要代理IP段就行了吗？

### ISSUE THREAD

**Issue by k1w1w1n** [huyyi/ggd#1]
RT

**Comment by huyyi** [comment]
是的

看你能不能ping通游戏内的服务器，以及延迟多少，我抓到的域名是这个：
`ap-northeast-2.gaggle.fun` 

直连延迟比较低

-------

正在 Ping ap-northeast-2.gaggle.fun [172.65.242.160] 具有 32 字节的数据:
来自 172.65.242.160 的回复: 字节=32 时间=64ms TTL=50
来自 172.65.242.160 的回复: 字节=32 时间=64ms TTL=50
来自 172.65.242.160 的回复: 字节=32 时间=64ms TTL=50
来自 172.65.242.160 的回复: 字节=32 时间=65ms TTL=50
来自 172.65.242.160 的回复: 字节=32 时间=64ms TTL=50
来自 172.65.242.160 的回复: 字节=32 时间=64ms TTL=50
来自 172.65.242.160 的回复: 字节=32 时间=63ms TTL=50

**Comment by k1w1w1n** [comment]
🫡
